# Generated by Django 5.2.8 on 2025-12-03 12:59

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Max size: 2MB', null=True, upload_to='avatars/', validators=[accounts.validators.validate_avatar_size]),
        ),
    ]
