# Generated by Django 6.0 on 2025-12-08 23:41

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallet", "0007_remove_transaction_wallet_tran_wallet__b97fb2_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("funding", "Funding"), ("purchase", "Purchase")],
                        help_text="Type of transaction (funding or purchase)",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount in Naira",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description (e.g., 'Paystack Deposit', 'MTN Airtime')",
                        max_length=255,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number (used for Paystack deposits)",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("failed", "Failed")],
                        default="completed",
                        help_text="Status: completed or failed",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="The wallet this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-timestamp"], name="transaction_wallet__3e896f_idx"
                    ),
                    models.Index(fields=["status"], name="transaction_status_71abbb_idx"),
                    models.Index(
                        fields=["transaction_type"], name="transaction_transac_09d7ec_idx"
                    ),
                ],
            },
        ),
    ]
