# Generated by Django 6.0 on 2025-12-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_requery_at',
            field=models.DateTimeField(blank=True, help_text='Last time we called the provider to recheck this transaction.', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_response',
            field=models.JSONField(blank=True, help_text='Last raw provider response for support/debugging.', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_status',
            field=models.CharField(blank=True, help_text='Latest known status from provider (e.g. delivered, pending, failed).', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requery_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this transaction has been rechecked with the provider.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requires_manual_review',
            field=models.BooleanField(default=False, help_text='Flag for customer support to manually review this transaction.'),
        ),
    ]
