# Generated by Django 5.2.8 on 2025-12-03 23:23

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(
                blank=True, help_text="Description of the transaction", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Transaction amount in Naira",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("pending", "Pending"), ("failed", "Failed")],
                default="pending",
                help_text="Current status of the transaction",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("credit", "Credit"), ("debit", "Debit")],
                help_text="Type of transaction",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                help_text="The wallet this transaction belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current wallet balance in Naira",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                default="NGN", help_text="Currency code (NGN for Naira)", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                help_text="The user who owns this wallet",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["wallet", "-timestamp"], name="wallet_tran_wallet__b97fb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="wallet_tran_status_a49b73_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["user"], name="wallet_wall_user_id_03e396_idx"),
        ),
    ]
