# Generated by Django 5.2.8 on 2025-12-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0003_transaction_purpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="purpose",
            field=models.CharField(
                choices=[("funding", "Funding"), ("purchase", "Purchase")],
                default="purchase",
                help_text="Purpose of the transaction (e.g. funding, purchase)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("funding", "Funding"), ("purchase", "Purchase")],
                help_text="Type of transaction",
                max_length=10,
            ),
        ),
    ]
